"""Phase 4 invariants for forecast-based trading and stochastic adoption."""

import numpy as np

from reflexive_market import adoption, simulate, traders
from reflexive_market.metrics import lag1_autocorr


def test_advanced_order_clips_to_position_cap():
    assert traders.advanced_order(0.05, risk_scale=0.001, q_cap=2.0) == 2.0
    assert traders.advanced_order(-0.05, risk_scale=0.001, q_cap=2.0) == -2.0


def test_advanced_order_returns_zero_for_nan_forecast():
    assert traders.advanced_order(float("nan"), risk_scale=0.001, q_cap=2.0) == 0.0


def test_advanced_order_passes_through_within_cap():
    out = traders.advanced_order(0.001, risk_scale=0.001, q_cap=2.0)
    assert abs(out - 1.0) < 1e-12


def test_stochastic_diffusion_with_zero_pi_and_delta_is_no_op():
    rng = np.random.default_rng(0)
    state = np.array([0, 1, 0, 1, 0])
    out = adoption.stochastic_diffusion_step(state, pi=0.0, delta=0.0, rng=rng)
    np.testing.assert_array_equal(out, state)


def test_stochastic_diffusion_pushes_population_to_full_adoption():
    rng = np.random.default_rng(1)
    state = np.zeros(500, dtype=int)
    for _ in range(2000):
        state = adoption.stochastic_diffusion_step(state, pi=0.01, delta=0.0, rng=rng)
    assert state.mean() > 0.95


def test_stochastic_diffusion_reaches_steady_state_with_exit():
    rng = np.random.default_rng(2)
    state = np.zeros(2000, dtype=int)
    for _ in range(3000):
        state = adoption.stochastic_diffusion_step(
            state, pi=0.02, delta=0.02, rng=rng
        )
    assert abs(state.mean() - 0.5) < 0.05


def test_simulate_run_default_kwargs_match_phase1_behaviour():
    a = simulate.run(
        T=200, N=64, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(11),
    )
    b = simulate.run(
        T=200, N=64, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(11),
    )
    np.testing.assert_array_equal(a["returns"], b["returns"])
    assert np.all(np.isnan(a["forecasts"]))
    assert np.all(a["adoption_share"] == 0.0)


def test_simulate_run_with_zero_adoption_and_forecast_matches_baseline():
    """Turning the forecast on but keeping zero adoption must not change the
    realised path, since adopters do not exist to act on the forecast."""
    base = simulate.run(
        T=600, N=64, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(7),
    )
    fc = simulate.run(
        T=600, N=64, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(7),
        forecast_window=100, forecast_p=1, risk_scale=0.001, q_cap=2.0,
        adoption_pi=0.0, adoption_delta=0.0, initial_adoption_share=0.0,
    )
    np.testing.assert_array_equal(base["returns"], fc["returns"])
    assert np.all(np.isnan(fc["forecasts"][:100]))
    assert np.all(np.isfinite(fc["forecasts"][100:]))


def test_adoption_share_rises_under_positive_pi():
    out = simulate.run(
        T=2000, N=200, mu=0.05, phi=0.20, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(17),
        forecast_window=100, forecast_p=1, risk_scale=0.001, q_cap=1.0,
        adoption_pi=0.005, adoption_delta=0.0,
    )
    assert out["adoption_share"][0] < 0.05
    assert out["adoption_share"][-1] > 0.95


def test_adoption_share_records_state_that_drove_outcomes():
    """adoption_share[t] must reflect the adopter state that actually
    generated returns[t]/demand[t]/profits[t], not the post-update state.
    Edge case: with adoption_pi = 1, returns[0] is generated by zero
    adopters (the initial state); the recorded adoption_share[0] must
    therefore be 0.0 even though the end-of-period-0 transition then
    flips every trader to an adopter."""
    out = simulate.run(
        T=5, N=10, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(0),
        forecast_window=2, forecast_p=1, risk_scale=0.001, q_cap=1.0,
        adoption_pi=1.0, adoption_delta=0.0,
    )
    assert out["adoption_share"][0] == 0.0
    np.testing.assert_array_equal(out["adoption_share"][1:], 1.0)


def test_null_profit_is_per_trader_not_population_mean():
    """null_profit[t] must be the realised profit of a single representative
    non-adopter (per eq 8), not the population mean of all N null draws times
    r. The population-mean version decays linearly in (1 - A) toward zero as
    adoption rises because adopter null draws are independent of the market,
    which biases the phase 7 null-relative endpoint and the phase 5 CE risk
    penalty.

    Edge case: when every trader is an adopter there is no non-adopter
    representative, so null_profit[t] must be NaN. With adoption_pi = 1 the
    first period generates outcomes under zero adoption (null_profit[0] is a
    finite single-trader draw), and every subsequent period is at full
    adoption (null_profit[1:] must be NaN).
    """
    out = simulate.run(
        T=5, N=10, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(0),
        forecast_window=2, forecast_p=1, risk_scale=0.001, q_cap=1.0,
        adoption_pi=1.0, adoption_delta=0.0,
    )
    assert np.isfinite(out["null_profit"][0])
    assert np.all(np.isnan(out["null_profit"][1:]))


def test_adoption_start_t_holds_indicators_then_releases():
    """With initial adoption at zero, no transitions can fire until
    ``adoption_start_t``. After that index the share rises as usual."""
    out = simulate.run(
        T=600, N=128, mu=0.05, phi=0.10,
        sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(0),
        adoption_pi=0.05, adoption_delta=0.0,
        adoption_start_t=200,
    )
    np.testing.assert_array_equal(out["adoption_share"][:200], 0.0)
    assert out["adoption_share"][-1] > 0.5


def test_adoption_start_t_does_not_change_market_path():
    """Delaying transitions must leave the realised return path identical
    when no adopters can act on the forecast yet."""
    common = dict(
        T=400, N=64, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
    )
    base = simulate.run(rng=np.random.default_rng(13), **common)
    delayed = simulate.run(
        rng=np.random.default_rng(13),
        adoption_pi=0.1, adoption_delta=0.0,
        adoption_start_t=300,
        **common,
    )
    np.testing.assert_array_equal(base["returns"], delayed["returns"])


def test_adoption_args_do_not_advance_market_rng():
    """No-op adoption settings, including pi=0 with delta>0 and zero initial
    adopters, must not change the exogenous market path. Otherwise across-
    regime comparisons would be confounded by different shock streams."""
    common = dict(
        T=400, N=64, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
    )
    base = simulate.run(rng=np.random.default_rng(123), **common)
    no_op = simulate.run(
        rng=np.random.default_rng(123),
        adoption_pi=0.0, adoption_delta=0.0, initial_adoption_share=0.0,
        **common,
    )
    delta_only = simulate.run(
        rng=np.random.default_rng(123),
        adoption_pi=0.0, adoption_delta=0.05, initial_adoption_share=0.0,
        **common,
    )
    np.testing.assert_array_equal(base["returns"], no_op["returns"])
    np.testing.assert_array_equal(base["returns"], delta_only["returns"])


def test_high_adoption_changes_lag1_autocorr_relative_to_baseline():
    """Sanity check the central mechanism: a long run with full adoption
    has a different empirical lag-1 autocorrelation than the same run with
    zero adoption. The direction depends on parameters; this test only
    asserts a non-trivial change."""
    common = dict(
        T=4000, N=200, mu=0.05, phi=0.25, sigma_news=0.01, sigma_q=1.0,
        forecast_window=250, forecast_p=1, risk_scale=0.001, q_cap=1.0,
    )
    base = simulate.run(rng=np.random.default_rng(31), **common)
    full = simulate.run(
        rng=np.random.default_rng(31),
        initial_adoption_share=1.0,
        **common,
    )
    rho_base = lag1_autocorr(base["returns"])
    rho_full = lag1_autocorr(full["returns"])
    assert abs(rho_base - rho_full) > 0.02


def test_demand_adjusted_return_recovers_structural_phi_at_full_adoption():
    """The central identity behind the dual-channel result: the
    demand-adjusted return x_{t+1} = r_{t+1} - mu D_t equals
    phi r_t + sigma eps_{t+1} by construction, so even at full adoption,
    where the realised lag-1 autocorrelation is amplified well above phi,
    regressing x_{t+1} on r_t must recover the structural phi and leave a
    residual with the news-shock scale."""
    mu, phi, sigma_news = 0.05, 0.25, 0.01
    out = simulate.run(
        T=8000, N=200, mu=mu, phi=phi, sigma_news=sigma_news, sigma_q=1.0,
        rng=np.random.default_rng(99),
        forecast_window=250, forecast_p=1, risk_scale=0.001, q_cap=0.05,
        initial_adoption_share=1.0,
    )
    r = out["returns"]
    x = r - mu * out["demand"]
    r_lag = r[:-1] - r[:-1].mean()
    x_next = x[1:] - x[1:].mean()
    beta = float(np.dot(r_lag, x_next) / np.dot(r_lag, r_lag))
    resid_std = float((x_next - beta * r_lag).std())

    assert lag1_autocorr(r) > phi + 0.05
    assert abs(beta - phi) < 0.03
    assert abs(resid_std - sigma_news) < 0.001


def test_null_profit_mean_is_own_impact():
    """A null trader's order moves the within-period quote by mu * q / N
    and the position is marked at the post-impact price, so the
    representative null profit has positive mean mu * sigma_q^2 / N, not
    zero. The phase 7 null-relative endpoint inherits this term, so pin it."""
    mu, sigma_q, N = 0.05, 1.0, 100
    means = [
        simulate.run(
            T=2000, N=N, mu=mu, phi=0.10, sigma_news=0.01, sigma_q=sigma_q,
            rng=np.random.default_rng(7000 + s),
        )["null_profit"].mean()
        for s in range(20)
    ]
    predicted = mu * sigma_q ** 2 / N
    assert abs(np.mean(means) - predicted) < 0.4 * predicted


def test_advanced_order_export_matches_profit_and_warmup():
    out = simulate.run(
        T=400, N=64, mu=0.05, phi=0.10, sigma_news=0.01, sigma_q=1.0,
        rng=np.random.default_rng(3),
        forecast_window=100, forecast_p=1, risk_scale=0.001, q_cap=1.0,
        initial_adoption_share=0.5,
    )
    np.testing.assert_allclose(
        out["advanced_profit"], out["advanced_order"] * out["returns"]
    )
    assert np.all(out["advanced_order"][:100] == 0.0)
    assert np.any(out["advanced_order"][100:] != 0.0)
